### ISSUE TITLE
Tragic server crash on join

### ISSUE THREAD

**Issue by Aresiel** [Talia-12/Hexal#2]
```
java.lang.NoClassDefFoundError: net/minecraft/class_742
	at ram.talia.hexal.fabric.cc.CCPlayerLinkstore.<init>(CCPlayerLinkstore.kt:25) ~[hexal-fabric-1.18.2-0.1.4.jar:?]
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.<init>(Unknown Source) ~[?:?]
```
Full crash report: [https://mclo.gs/FYJX97p](https://mclo.gs/FYJX97p)

Happens every time I join my server, only the server crashes. Does not happen when joining single player on the client. Identical mod (& mod config) setups on both. Same fabric loader version too.

**Comment by Talia-12** [comment]
Alright, this *should* be fixed in [v0.1.5](https://github.com/Talia-12/Hexal/releases/tag/0.1.5), thanks for sending the bug report
