### ISSUE TITLE
Hexal on fabric breaks the Hex Book (0.1.6)

### ISSUE THREAD

**Issue by noukherne** [Talia-12/Hexal#5]
Hi. I've been trying to update to the new version but something about the everbook seems to break the manual, making it impossible to read any chapter of it. 

Here is the part of the log related to the issue:

[21:15:39] [Render thread/ERROR]: Error compiling book hexcasting:thehexbook, using empty contents
java.lang.RuntimeException: Error building entry hexal:patterns/everbook_entries
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:225) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at net.minecraft.class_632.handler$zmh000$patchouli_onSync(class_632.java:1017) ~[client-intermediary.jar:?]
	at net.minecraft.class_632.method_2861(class_632.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11130(class_634.java:1211) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11925(class_2779.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11054(class_2779.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry hexal:patterns/everbook_entries page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:250) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	... 31 more
Caused by: java.lang.RuntimeException: Failed to create custom component ram.talia.hexal.interop.patchouli.EverbookPatternComponent
	at vazkii.patchouli.client.book.template.component.ComponentCustom.onVariablesAvailable(ComponentCustom.java:31) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.VariableAssigner.assignVariableHolders(VariableAssigner.java:48) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.TemplateComponent.compile(TemplateComponent.java:50) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:114) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	... 31 more
Caused by: java.lang.NullPointerException
	at ram.talia.hexal.fabric.cc.CCEverbook.getClientPattern(CCEverbook.kt:77) ~[hexal-fabric-1.18.2-0.1.6.jar:?]
	at ram.talia.hexal.fabric.xplat.FabricClientXplatImpl.getClientEverbookPattern(FabricClientXplatImpl.java:109) ~[hexal-fabric-1.18.2-0.1.6.jar:?]
	at ram.talia.hexal.interop.patchouli.EverbookPatternComponent.getPatterns(EverbookPatternComponent.kt:30) ~[hexal-fabric-1.18.2-0.1.6.jar:?]
	at at.petrak.hexcasting.interop.patchouli.AbstractPatternComponent.onVariablesAvailable(AbstractPatternComponent.java:49) ~[hexcasting-fabric-1.18.2-0.9.4.jar:?]
	at vazkii.patchouli.client.book.template.component.ComponentCustom.onVariablesAvailable(ComponentCustom.java:29) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.VariableAssigner.assignVariableHolders(VariableAssigner.java:48) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.TemplateComponent.compile(TemplateComponent.java:50) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:114) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:28) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1-FABRIC.jar:?]
	... 31 more

**Comment by Talia-12** [comment]
Thanks for the report, this is now fixed in release 0.1.7!
